apiVersion: v1
kind: Service
metadata:
  name: {{ include "kumo.fullname" . }}
  labels:
    {{- include "kumo.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 4566
      targetPort: http
      protocol: TCP
  selector:
    {{- include "kumo.selectorLabels" . | nindent 4 }}
